// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_AC-aF9HnhXn7Y30sexkq55fUfdFXXlc',
    appId: '1:859513315275:web:3b99bf2c052212bc32e04e',
    messagingSenderId: '859513315275',
    projectId: 'safelink-85a6c',
    authDomain: 'safelink-85a6c.firebaseapp.com',
    storageBucket: 'safelink-85a6c.firebasestorage.app',
    measurementId: 'G-49PVHN4B56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbiDOqXxYBPxuHWrVWgu8CuOAwSK1ccXs',
    appId: '1:859513315275:android:e7a3ed6efde75d8132e04e',
    messagingSenderId: '859513315275',
    projectId: 'safelink-85a6c',
    storageBucket: 'safelink-85a6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Apv4SdHS-B3jqRe49zXe3hLhsFTUj38',
    appId: '1:859513315275:ios:17d8f48e58d6cb1f32e04e',
    messagingSenderId: '859513315275',
    projectId: 'safelink-85a6c',
    storageBucket: 'safelink-85a6c.firebasestorage.app',
    iosBundleId: 'com.safelink.safelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Apv4SdHS-B3jqRe49zXe3hLhsFTUj38',
    appId: '1:859513315275:ios:17d8f48e58d6cb1f32e04e',
    messagingSenderId: '859513315275',
    projectId: 'safelink-85a6c',
    storageBucket: 'safelink-85a6c.firebasestorage.app',
    iosBundleId: 'com.safelink.safelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_AC-aF9HnhXn7Y30sexkq55fUfdFXXlc',
    appId: '1:859513315275:web:cf21684185342c0132e04e',
    messagingSenderId: '859513315275',
    projectId: 'safelink-85a6c',
    authDomain: 'safelink-85a6c.firebaseapp.com',
    storageBucket: 'safelink-85a6c.firebasestorage.app',
    measurementId: 'G-HGDRJY7M26',
  );
}
